### ISSUE TITLE
Unit tests fail on Windows

### ISSUE THREAD

**Issue by baratali** [checkstyle/patch-filters#113]
Some unit tests fail on Windows (in cmd, git bash, ubuntu wsl). Works fine on Linux though.
```
Failed tests:   testFileTabCharacterMoveCodeInSameFileWithMinorChanges(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilterTest): error message 0 expected:<[C:\Users\Baratali\git\patch-filters\src\test\resources\com\puppycrawl\tools\checkstyle\filters\suppressionpatchfilter\FileTabCharacter\MoveCodeInSameFileWithMinorChanges\newline/Test.java:19:25: Line contains a tab character].> but was:<[Audit done].>
  testLineLength(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilterTest): error message 0 expected:<[C:\Users\Baratali\git\patch-filters\src\test\resources\com\puppycrawl\tools\checkstyle\filters\suppressionpatchfilter\LineLength\newline/Test.java:10: Line is longer than 80 characters (found 163)].> but was:<[Audit done].>
  testOrderedProperties(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilterTest): error message 0 expected:<[C:\Users\Baratali\git\patch-filters\src\test\resources\com\puppycrawl\tools\checkstyle\filters\suppressionpatchfilter\OrderedProperties\newline/test.properties:6: Property key 'key.pag' is not in the right order with previous property 'key.png'].> but was:<[Audit done].>
  testFileTabCharacterSingleChangedLine(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilterTest): error message 0 expected:<[C:\Users\Baratali\git\patch-filters\src\test\resources\com\puppycrawl\tools\checkstyle\filters\suppressionpatchfilter\FileTabCharacter\SingleChangedLine\patchedline/Test.java:19:25: Line contains a tab character].> but was:<[Audit done].>
  testRegexpSingleline(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilterTest): error message 0 expected:<...xpSingleline\newline[/]Input.java:12: Line ...> but was:<...xpSingleline\newline[\]Input.java:12: Line ...>
  testFileTabCharacterMoveCodeInSameFileWithoutChanges(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilterTest): error message 0 expected:<[C:\Users\Baratali\git\patch-filters\src\test\resources\com\puppycrawl\tools\checkstyle\filters\suppressionpatchfilter\FileTabCharacter\MoveCodeInSameFileWithoutChanges\newline/Test.java:19:25: Line contains a tab character].> but was:<[Audit done].>
  testFileTabCharacter(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilterTest): error message 0 expected:<[C:\Users\Baratali\git\patch-filters\src\test\resources\com\puppycrawl\tools\checkstyle\filters\suppressionpatchfilter\FileTabCharacter\newline/Test.java:21:25: Line contains a tab character].> but was:<[Audit done].>
  testFileTabCharacterSingleNewLine(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilterTest): error message 0 expected:<[C:\Users\Baratali\git\patch-filters\src\test\resources\com\puppycrawl\tools\checkstyle\filters\suppressionpatchfilter\FileTabCharacter\SingleNewLine\newline/Test.java:20:25: Line contains a tab character].> but was:<[Audit done].>
  testMethodName(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchXpathFilterTest): error message 0 expected:<[C:\Users\Baratali\git\patch-filters\src\test\resources\com\puppycrawl\tools\checkstyle\filters\suppressionpatchxpathfilter\MethodName\newline/Test.java:4:17: Name 'MyMethod' must match pattern '^[a-z][a-zA-Z0-9]*$'].> but was:<[Audit done].>
  testAvoidNestedBlocks(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchXpathFilterTest): error message 0 expected:<[C:\Users\Baratali\git\patch-filters\src\test\resources\com\puppycrawl\tools\checkstyle\filters\suppressionpatchxpathfilter\AvoidNestedBlocks\patchedline/Test.java:5:9: Avoid nested blocks].> but was:<[Audit done].>
  testMagicNumber(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchXpathFilterTest): error message 0 expected:<[C:\Users\Baratali\git\patch-filters\src\test\resources\com\puppycrawl\tools\checkstyle\filters\suppressionpatchxpathfilter\MagicNumber\patchedline/Test.java:5:20: '256' is a magic number].> but was:<[Audit done].>
  testIllegalToken(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchXpathFilterTest): error message 0 expected:<[C:\Users\Baratali\git\patch-filters\src\test\resources\com\puppycrawl\tools\checkstyle\filters\suppressionpatchxpathfilter\IllegalToken\newline/Test.java:15:14: Using 'outer:' is not allowed].> but was:<[Audit done].>
  testStrategyOptionOnEclipse(com.puppycrawl.tools.checkstyle.jgit.GitDiffOnOpenSourceTest): Audit event should be rejected when there are no matching patch filters ==> expected: <true> but was: <false>
  testInsertDeleteReplaceEditTypesWithinHunk(com.puppycrawl.tools.checkstyle.jgit.GitDiffWithContextSizeDefaultTest): expected:<3> but was:<0>
  testMultopleFilesWithMultipleHunks(com.puppycrawl.tools.checkstyle.jgit.GitDiffWithContextSizeDefaultTest): expected:<2> but was:<1>

Tests in error:
  testNewlineAtEndOfFile(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilterTest): Invalid id: 0047b33
  testFileLength(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilterTest): Invalid id: 67782f7
  testRegexpOnFilename(com.puppycrawl.tools.checkstyle.filters.SuppressionPatchFilterTest): Invalid id: 86748d4
  testHaveRemovedFile(com.puppycrawl.tools.checkstyle.jgit.GitDiffWithContextSizeDefaultTest): Invalid id: 0000000
  testHaveRemovedFile(com.puppycrawl.tools.checkstyle.jgit.GitDiffWithContextSizeZeroTest): Invalid id: 0000000

Tests run: 42, Failures: 15, Errors: 5, Skipped: 6
```

Interesting error on parsing a patch file:
```
testHaveRemovedFile(com.puppycrawl.tools.checkstyle.jgit.GitDiffWithContextSizeZeroTest)  Time elapsed: 0 sec  <<< ERROR!
org.eclipse.jgit.errors.InvalidObjectIdException: Invalid id: 0000000
        at org.eclipse.jgit.lib.AbbreviatedObjectId.fromHexString(AbbreviatedObjectId.java:151)
        at org.eclipse.jgit.lib.AbbreviatedObjectId.fromString(AbbreviatedObjectId.java:108)
        at org.eclipse.jgit.patch.FileHeader.parseIndexLine(FileHeader.java:607)
        at org.eclipse.jgit.patch.FileHeader.parseGitHeaders(FileHeader.java:507)
        at org.eclipse.jgit.patch.Patch.parseDiffGit(Patch.java:243)
        at org.eclipse.jgit.patch.Patch.parseFile(Patch.java:196)
        at org.eclipse.jgit.patch.Patch.parse(Patch.java:178)
        at org.eclipse.jgit.patch.Patch.parse(Patch.java:151)
        at com.puppycrawl.tools.checkstyle.jgit.AbstractJgitPatchParserEvaluationTest.loadPatch(AbstractJgitPatchParserEvaluationTest.java:35)
        at com.puppycrawl.tools.checkstyle.jgit.GitDiffWithContextSizeZeroTest.testHaveRemovedFile(GitDiffWithContextSizeZeroTest.java:111)
```

**Comment by romani** [comment]
I lower priority, as it is problem in library or in our patch that is shared between different OSs.

**Comment by romani** [comment]
@baratali , does it sound like limitation of library or we need proper(Windows like) line ends in patch files? 
does it mean that filters will not work in Windows ?

we can adjust git to checkout/clone/pill such files in OS specific line ends.

**Comment by baratali** [comment]
I reviewed jgit sources of Patch class, and looks like it works only with Linux style newlines. It reads a patch file using `RawParseUtils.nextLF()` method which doesn't care about CR symbol for windows-style newlines (CRLF), so CR symbol becomes a part of the readed line. Also seems like Patch class doesn't know about jgit `core.autocrlf` system property.

I will try to configure recources with `.gitattributes` to support only LF line endings.

**Comment by romani** [comment]
Here you is bunch of examples https://github.com/checkstyle/checkstyle/blob/master/.gitattributes

**Comment by romani** [comment]
might be same problem - https://github.com/checkstyle/eclipse-cs/pull/395

**Comment by rnveach** [comment]
I am trying to atleast peek into the git's source code as I have egit on Eclipse and it doesn't fail with an exception on a patch. I have not found anything yet.

What we can do is surround the input stream sent to `patch.parse` with a wrapper, that will proxy out the `\r` issue.
https://github.com/checkstyle/patch-filters/blob/42c30582f1fb4e669368028e9eddfa924c12148f/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionJavaPatchFilter.java#L227

**Comment by rnveach** [comment]
Issue 2)
`AbstractPatchFilterEvaluationTest` is failing because "Audit Done." is part of the output when it isn't expected. I can see the other violation in memory, so the expected violation appears to be there.

I'll update more as I find the cause.

**Comment by rnveach** [comment]
Issue 4)
https://github.com/checkstyle/patch-filters/blob/master/src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionpatchfilter/RegexpMultiline/newline/defaultContextConfig.xml#L8
Some tests are specifically made for Linux by the settings in the configuration.

**Comment by rnveach** [comment]
Issue 5)
https://github.com/checkstyle/patch-filters/blob/42c30582f1fb4e669368028e9eddfa924c12148f/src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/coding/HiddenField/newline/defaultContext.patch#L3
https://github.com/checkstyle/patch-filters/blob/42c30582f1fb4e669368028e9eddfa924c12148f/src/main/java/com/puppycrawl/tools/checkstyle/filters/JavaPatchFilterElement.java#L186
https://github.com/checkstyle/patch-filters/blob/42c30582f1fb4e669368028e9eddfa924c12148f/src/main/java/com/puppycrawl/tools/checkstyle/filters/SuppressionPatchFilterElement.java#L79

Test patches must be OS specific because we match them nearly exactly as to what we receive from Checkstyle's audit events.
Example test patch has `/` but audit event has `\`.

**Comment by rnveach** [comment]
After my latest PR, https://github.com/checkstyle/patch-filters/issues/113#issuecomment-1312808670 is the only thing remaining. I am not sure yet on the best approach to fixing it.
