### ISSUE TITLE
No such file or directory when trying to build a report

### ISSUE THREAD

**Issue by rdiachenko** [checkstyle/patch-filters#43]
```
java.io.FileNotFoundException: /xxx/workspace/patch-filters/DiffReport/index.html (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
	at com.github.checkstyle.generatepatchfile.GeneratePatchFile.generateSummaryIndexHtml(GeneratePatchFile.java:318)
	at com.github.checkstyle.generatepatchfile.GeneratePatchFile.generatePatch(GeneratePatchFile.java:164)
	at com.github.checkstyle.generatepatchfile.GeneratePatchFileLauncher.main(GeneratePatchFileLauncher.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:128)
```
After creating `DiffReport` folder manually the generator starts working.

If there is no such folder it should be created automatically without giving the above exception.

**Comment by rdiachenko** [comment]
Tried latest master, looks like fixed.

**Comment by rdiachenko** [comment]
Reopening as the aforementioned is reproduced when the last argument (runPatchNum) for `GeneratePatchFileLauncher` is 1

**Comment by HuGanghui** [comment]
@rdiachenko I will add description in README.md that the last parameter which represent num of patch-filter report between two commits should `>1`

> # num of patch-filter report between two commits will be created
> # example is 4, then three reports will be created.
> 4 

And if you set 1, then 0 report will be created, so the failure above will happen. https://github.com/checkstyle/patch-filters/blob/27fb2668fc595a8db86896adecd7a572814e0397/src/main/java/com/github/checkstyle/generatepatchfile/GeneratePatchFile.java#L159-L165

**Comment by rdiachenko** [comment]
1. Please make it clear in README
2. Throw `IllegalArgumentException` within `generatePatch` if `runPatchNum` is not correct

**Comment by HuGanghui** [comment]
@rdiachenko done in #51

**Comment by rdiachenko** [comment]
Fix is merged.
